apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magicevents-ingress
  namespace: magicevents
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "$http_origin"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: magicevents.com
      http:
        paths:
          - path: /api/events(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: events-management-service
                port:
                  number: 8080
          - path: /api/eventsetup(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: eventsetup-service
                port:
                  number: 8086
          - path: /api/boards(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: board-service
                port:
                  number: 8081
          - path: /api/games(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: guest-game-service
                port:
                  number: 8083
          - path: /api/galleries(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gallery-service
                port:
                  number: 8085

